title: Mohamed Mahdi # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <br>Welcome!
  <br>Im am an computer science engineering student currently in my last few months 
  attending <br> KTH Royal Institute of Technology in Stockholm, Sweden.
  <br>
  <br>Here you can see a short summary of my work so far!<br>
  
  <a href="https://www.linkedin.com/in/mohamed-mahdi-762b08183/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
